spring:
  application:
    name: ribbon-consumer

server:
  port: 8764

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:1515/eureka/

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream