server:
  port: 8259
spring:
  application:
    name: service-hi
    # mysql
  datasource:
    url: jdbc:mysql://localhost:3306/dzc?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  hbm2ddl:
    auto: update
entitymanager:
  packagesToScan: client

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1515/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}


